# Site settings
title: Lambdaspace workshop
email: dimitrispl96@gmail.com
description: >
    This is a a short desc.
baseurl: ""
url: "githubpages-boilerplate"
twitter_username: lambdaspace
github_username:  lambdaspace

# Build settings
markdown: kramdown

include: ['_pages']
